### PR TITLE
Migrate to pydantic 2.0

### LINKED ISSUE #276: [FEATURE] Support Pydantic 2.0
**Is your feature request related to a problem? Please describe.**
pydantic v2 [got released](https://github.com/pydantic/pydantic/releases). 
However, fastapi-utils has a `pydantic<2.0` constraint: https://github.com/dmontagu/fastapi-utils/blob/3ef27a6f67ac10fae6a8b4816549c0c44567a451/pyproject.toml#L43

 
**Describe the solution you'd like**
I would like to be able to use pydantic v2 and fastapi-utils together. Can we build the support for pydantic v2?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pavelzw**
Closes #276

### CODE REVIEW

**Comment by jonashaag** [comment]
Is it possible to keep supporting Pydantic 1?

**Comment by pavelzw** [comment]
I don't think that we can specify "install `pydantic-settings` only if `pydantic < 2.0`" in poetry...

**Comment by pavelzw** [comment]
@dmontagu could you take a look at this PR please?

**Comment by jonashaag** [comment]
Would be a real bummer to drop Pydantic 1 support... Pydantic 1 is going to be used by lots of people for a few years.

**Comment by pavelzw** [comment]
I think adding pydantic-settings as an optional dependency is the best compromise.

**Comment by kgadek93** [comment]
Hi,
I really need these changes. Can we somehow speed up the review and release process? 🙏

**Comment by pavelzw** [comment]
Pinging @dmontagu for visibility.

**Comment by pavelzw** [comment]
https://github.com/yuval9313/FastApi-RESTful is a fork of fastapi-utils that is more active and already has support for pydantic 2. Feel free to check it out.

**Comment by ohmeow** [comment]
Any update on this?

Thanks!

**Pull request closed without merging**
