### PR TITLE
SQLAlchemy 2.0 Compatability

### PR DESCRIPTION
**Pull request by ZachMyers3**
Hello!

[Following the SQLA2.0 migration guide](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html) I walked through where SQLAlchemy was used in the codebase and it appears no changes were needed.

To further test this I install the latest version of SQLAlchemy (2.0.12 as of this request) and ran the test cases with no issues.

Something worth mentioning is [conftest.py](./tests/conftest.py) defines `User` with `1.14` column definitions rather than the future state of `2.0+`. These are still accepted in the current version of SQLA2 so it currently raises no issues. I believe it's a good idea to keep them like this until future versions of SQLAlchemy force a change here.

Willing to do whatever else is needed to get this in, thanks for the great library!

For #270

### CODE REVIEW

**Comment by lociko** [comment]
Hi, I hope you are doing well! 
Is there any update?

**Review by hassanj-576 — APPROVED** [review]

**Comment by ZachMyers3** [comment]
I've been running this branch of changes in a production environment with SQLA 2.0 since I created the MR to validate testing a bit. It's working as expected. Thanks for the project!

**Comment by hassanj-576** [comment]
So, any chance of this getting merged ?

**Comment by ameyarao98** [comment]
hello, can this be merged?

**Comment by pavelzw** [comment]
https://github.com/yuval9313/FastApi-RESTful is a more active fork of this repo that already has slqalchemy 2 support since `0.5.0` https://github.com/yuval9313/FastApi-RESTful/pull/202.

**Pull request closed without merging**
